#! /bin/sh

# bspwm setup
bspc monitor -d I II III IV V VI VII

bspc config border_width         4
bspc config window_gap          25

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 25
bspc config border_radius 15

bspc config focused_border_color "#80C2C0"
bspc config active_border_color "#80C2C0"
bspc config normal_border_color "#0C363F"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Other setups

# compositor
killall -q picom; picom --experimental-backends --config ~/.config/picom/picom.conf &

# sxhkd (Hot Key Daemon)
killall -q sxhkd; sxhkd &

# dunst (Notification Daemon)
killall -q dunst; dunst -conf ~/.config/dunst/dunstrc &

# polybar
~/.config/polybar/launch.sh &

# wallpaper
DISPLAY=:0 feh --bg-max --randomize ~/Pictures/Wallpaper/*
